updated `int(` to `parse(Int,`
The current example gives this error when you pass an argument: 

ERROR: LoadError: UndefVarError: `int` not defined

This is because you can't directly cast `String`s as `Int`s. I've updated to code to appropriately call `parse` to do the conversion.